[build]
  # This will be run the site build
  command = "npm run start"
  # This is the directory is publishing to netlify's CDN
  publish = "public"
  # functions build directory
  functions = "functions-build"